name: Python x402 A2A

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python/x402_a2a
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Python 3.11
        run: uv python install 3.11

      - name: Install dependencies
        run: uv sync --group lint

      - name: Lint
        run: uvx ruff check --output-format=github .

      - name: Format
        run: uvx ruff format --check .
